repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog – detect & verify secrets
        entry: |
          bash -c 'trufflehog git file://. \
            --since-commit main \
            --only-verified \
            --fail'
        language: system
        stages: [pre-commit, pre-push]

