repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.3
    hooks:
      - id: gitleaks
        name: Gitleaks – scan staged changes for hardcoded secrets
        entry: gitleaks protect --staged --verbose
        language: golang

  - repo: local
    hooks:
      - id: trufflehog-verify-gitleaks
        name: TruffleHog – verify Gitleaks findings
        entry: ./scripts/verify_secrets_with_trufflehog.sh
        language: script
        always_run: true
        pass_filenames: false
        stages: [pre-commit, pre-push]

