repos:
  - repo: local
    hooks:
      - id: trufflehog-detect-only
        name: TruffleHog – detect secrets (regex only)
        description: Scan your Git repo for any secret patterns and fail on match (no validation).
        entry: >
          bash -c "trufflehog git file://$(pwd) --since-commit main --branch HEAD --fail"
        language: system
        pass_filenames: false
        stages: [pre-commit, pre-push]
