repos:
  - repo: local
    hooks:
      - id: trufflehog-scan
        name: TruffleHog – detect all secrets
        description: Scan your entire Git history for any secrets and fail on match.
        entry: >
          bash -c '
            trufflehog git file://$(pwd) \
              --fail
          '
        language: system
        stages: [commit, push]
